use edi;

DROP TABLE if exists DOC_MEMORANDUM;
DROP TABLE if exists DOC_MESSAGE;
DROP TABLE if exists BP_EXECUTOR_TASK_FOLDER_STRUCTURE;
DROP TABLE if exists BP_SEQUENCE;
DROP TABLE if exists hibernate_sequence;
DROP TABLE if exists CAT_UPLOADED_FILE;

DROP TABLE if exists BP_EXECUTOR_TASK;
DROP TABLE if exists BP_BUSINESS_PROCESS;
DROP TABLE if exists NUMERATION;
DROP TABLE if exists DOC_ABSTRACT_DOCUMENT_EDI;
DROP TABLE if exists CAT_USER;
DROP TABLE if exists CAT_DEPARTMENT;
DROP TABLE if exists CAT_POSITION;